package response

import (
	"reflect"
)

const (
	SUCCESS                    = 200
	ERROR                      = 400
	AUTH_FAIL                  = 401
	EXPIRED_TOKEN              = 402
	INVALID_TOKEN              = 403
	NOT_EXIST_TOKEN            = 405
	VALID_TOKEN_NO_FOUND       = 406
	DUPLICATE_EMAIL            = 500
	AUTH_CODE_INVALID          = 501
	EMAIL_PASSWORD_NOT_MATCH   = 502
	FAILED_SEND_MAIL           = 503
	INVALID_EMAIL              = 504
	INVALID_PASSWORD           = 505
	NOT_FOUND_EMAIL            = 506
	NOT_FOUND_REDIS_KEY        = 507
	INVALID_CHAR               = 508
	DUPLICATE_WORKSPACE_DOMAIN = 509
	INVALID_LOGIN              = 510

	DUPLICATE_WORKSPACE  = 512
	NO_MEMBERS_WORKSPACE = 513
	NOT_FOUND_WORKSPACE  = 514

	DUPLICATE_CHANNEL = 516
	NOT_INVITED_EMAIL = 517

	INVALID_CHANNEL   = 521
	INVALID_FILE_SIZE = 522

	TOKEN_INVALID          = 524
	NOT_LEAVE_CHANNEL      = 525
	CHANNEL_HOST_AUTH_FAIL = 526
	MASTER_AUTH_FAIL       = 527
	DUPLICATE_URL          = 528
	NOT_FIND_PROFILE       = 529

	PASSWORD_NOT_MATCH = 532
	INVALID_IMAGE      = 533

	INVALID_PROJECT          = 535
	DUPLICATE_PROJECT        = 536
	PROJECT_HOST_AUTH_FAIL   = 537
	INVALID_WORKSPACE_ACCESS = 538

	INVALID_PROJECT_JOIN     = 540
	DUPLICATE_TAG            = 541
	DUPLICATE_MEMBER         = 542
	INVALID_PRIVATE_PROJECT  = 543
	JOIN_PROJECT             = 544
	NOT_ALLOWED_CHAR         = 545
	INVALID_PARAMETER        = 600
	SWIT_ERROR               = 601
	NOT_FOUND_DATA           = 602
	INVALID_ACCESS_TOKEN     = 603
	VALIDATION_ERROR         = 604
	SWIT_ERROR_MODEL         = 605
	FAILED_SAVE              = 606
	FAILED_UPDATE            = 607
	FAILED_DELETE            = 608
	DUPLICATE_DATA           = 609
	DELETED_CHANNEL          = 610
	INVALID_WORDS            = 611
	INVAILD_ARCHIVED_CHANNEL = 612
	INVAILD_ARCHIVED_PROJECT = 613
	INVALID_PROJECT_COUNT    = 614
	INVALID_TASK_COUNT       = 615
	INVALID_TRIAL_PERIOD     = 616
	EXPIRED_FILE             = 617
	CAPACITY_EXCEEDED        = 618
	NO_FOUND_INFORMATION     = 619
	FAILED_DELETE_CATEGORY   = 700
	FAIL_ANALYSIS_BATCH      = 800
	NOT_UPLOAD_SIZE          = 1000
	IMPORT_FILE_ERROR        = 1001
	EXIST_IN_PROGRESS_IMPORT = 1002
	INVALID_DOWNLOAD_LINK    = 1003
	INVALID_IMPORT           = 1004
	EXIST_IN_ACTION_IMPORT   = 1005

	INVALID_DOMAIN                = 1100
	INVALID_DOMAIN_COUNT          = 1101
	INVALID_DOMAIN_PUBLIC         = 1102
	INVALID_PASSWORD_CHAR         = 1103
	INVALID_PASSWORD_SPECIAL_CHAR = 1104
)

//JSONResponse JSONResponse
func NvlArray(data interface{}) interface{} {
	if reflect.ValueOf(data).Len() == 0 {
		return []string{}
	}
	return data
}
